services:
  # Web Service
  - type: web
    name: maintenance-scheduler
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: maintenance-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

  # PostgreSQL Database
  - type: pgsql
    name: maintenance-db
    databaseName: maintenance_db
    plan: free  # Change to 'starter' for production